pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f Jenkins/Jenkins_project/maven_tomcat/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }

        stage('Create Tomcat Docker Image'){
            steps {
                sh "pwd"
                sh "ls -a"
                sh "docker build ./Jenkins/Jenkins_project/jenkin_tomcat_sample_docker -t tomcatsamplewebapp:${env.BUILD_ID}"
            }
        }

    }
}