version: '3.8'
services:
  distro:
    image: alpine:latest
    restart: always #container will restart if there is any error
    container_name: custom_alpine #custom image name
    entrypoint: tail -f /dev/null #tail -f is an ongoing process, so it will run indefinitely and prevent the container from sleeping. The default entrypoint is overridden to keep the container running

  database:
    image: postgres:latest
    restart: always
    container_name: postgres_db
    ports:
    - "5432:5432"
    volumes: 
    - ../dump:/tmp
  
  web:
    image: nginx:latest
    restart: always
    container_name: nginx_web
    ports:
    - "8080:80"
    volumes:
    - ./mysite.template:/etc/nginx/conf.d/mysite.template
    environment: 
    - NGINX_HOST=sample.com
    - NGINX_PORT=80
    links:
    - database:db
    - distro

volumes:
  data:
    external: true #tells docker to use pre-existing external data volume if not return error
    