pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f Jenkins/Jenkins_project/maven_tomcat/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        
    }
}