pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f Jenkins/Jenkins_project/maven_tomcat/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
                build job: 'Deploy_application_stagging_env'

            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
                build job: 'Deploy_application_prod_env'
            }
        }
    }
}